### ISSUE TITLE
Doesn't sniff when released as part of a exrm elixir release

### ISSUE THREAD

**Issue by robacourt** [msantos/ewpcap#5]
Hi Michael

We're using ewpcap in our Elixir project (we were using epcap but we do need cross-platform support). It works fine until we do a release (using exrm) when ewpcap.open returns { ok .. } but we receive no messages. Do you have any idea how we might troubleshoot this?

Many thanks

Rob

**Comment by msantos** [comment]
Check beam has permissions to open the device and that the expected device is being used.

Depending on how the release was done, beam might be part of the release archive. If you're using file capabilities, the permissions will be removed when beam is copied. If you're using sudo, the path to beam will have to be updated in sudoers.conf.

About the weird ok return value: open/0 will use the default device for the system. The default device depends on the user privileges:

~~~ elixir
# As an unpriv'ed user
iex(1)> :ewpcap.getifaddrs()
{:ok, [{'bluetooth0', [description: 'Bluetooth adapter number 0']}]}
iex(2)> :ewpcap.dev()
{:ok, 'bluetooth0'}

iex(3)> :ewpcap.open()
{:ok, {:ewpcap_resource, #Reference<0.0.2.90>, ""}}
iex(4)> :ewpcap.open("eth0")
{:error, 'socket: Operation not permitted'}
~~~

Running the above using `sudo iex`:
~~~ elixir
iex(1)> :ewpcap.getifaddrs()
{:ok,
 [{'eth0', ...}, ...]}
iex(2)> :ewpcap.dev()
{:ok, 'eth0'}

iex(3)> :ewpcap.open("eth0")
{:ok, {:ewpcap_resource, #Reference<0.0.4.114>, ""}}
~~~

Just guessing, so let me know if you still have problems or you have any questions!

**Comment by robacourt** [comment]
Thanks for your quick response, Michael!

Turns out our issue was due to us not keeping the pid returned by :ewpcap.open. I'm assuming garbage collection stops the ewpcap process if we do not keep hold of the pid.

**Comment by msantos** [comment]
Glad you figured it out, hadn't thought of that!

Yes, exactly, NIFs can allocate resources for the library internal state. The resource is opaque: it looks like an empty binary but isnt:
~~~ elixir
iex(3)> :ewpcap.open()
{:ok, {:ewpcap_resource, #Reference<0.0.2.90>, ""}} # "" is the reference to the library internal state
~~~
So it is better to pass around the full tuple between processes. When the final process holding the resource exits, the resource will be freed.

**Comment by robacourt** [comment]
Great. Thanks for clearing that up!
