### ISSUE TITLE
can't compile

### ISSUE THREAD

**Issue by alexshavelev** [msantos/ewpcap#8]
alex_shavelev@lucky:~/projects/ewpcap$ rebar3 compile
===> Fetching pc ({pkg,<<"pc">>,<<"1.2.0">>})
===> Downloaded package, caching at /home/alex_shavelev/.cache/rebar3/hex/default/packages/pc-1.2.0.tar
===> Compiling pc
===> Verifying dependencies...
===> Compiling ewpcap
===> Compiling /home/alex_shavelev/projects/ewpcap/c_src/ewpcap.c
===> /home/alex_shavelev/projects/ewpcap/c_src/ewpcap.c:709:39: error: ‘ERL_NIF_DIRTY_JOB_IO_BOUND’ undeclared here (not in a function)
     {"pcap_close", 1, nif_pcap_close, ERL_NIF_DIRTY_JOB_IO_BOUND},

**Comment by msantos** [comment]
What version of erlang are you using?

Try compiling without dirty scheduler support:
~~~
CC="cc -DEWPCAP_DISABLE_DIRTY_SCHEDULER" rebar3 do clean, compile
~~~

**Comment by alexshavelev** [comment]
18.2
on thurday-friday everything worked fine

**Comment by alexshavelev** [comment]
without dirty also works now

**Comment by msantos** [comment]
I made a change recently to put close/1 on a dirty scheduler:
https://github.com/msantos/ewpcap/commit/901e7f6f6751c630e5104b74f6a1af51ff6c7f46

I'll make use of the dirty scheduler conditional on ERL_NIF_DIRTY_JOB_IO_BOUND being defined.

**Comment by alexshavelev** [comment]
cool
